### ISSUE TITLE
Out of sync -PyGame window and CarlaViz

### ISSUE THREAD

**Issue by Basavaraj-PN** [mjxu96/carlaviz#10]
Carla PyGame image and CarlaViz are out of sync 

![Screenshot from 2020-10-08 17-02-22](https://user-images.githubusercontent.com/23361336/95453275-27a10b80-0988-11eb-9a77-5ff727c30571.png)

**Comment by wx9698** [comment]
Hi, there are three main reasons that cause this latency:

1. Frontend: browser's single-threaded execution makes the performance improvements trickier. It can only use one core to do all stuffs like parsing data and rendering the images.
2. Backend: the backend needs to receive the data from Carla server, transform the data and then sends to the frontend.
3. Data transmission: the data is transmitted in this way: Carla server -> CarlaViz backend -> CarlaViz frontend. All these transmissions will introduce latency even in the loopback network (data copy etc...).

I have tried my best to optimize the backend but the other two parts are not in the scope of this application. I would suggest not trusting CarlaViz's camera images in latency-sensitive scenarios and only use them as indicators or visualizers in intensive simulation tasks.

**Comment by wx9698** [comment]
@Basavaraj-PN Hi, I just updated the repo and pushed a latest docker image to solve this problem. Please check mjxu96/carlaviz:latest image to see if that solves this problem from your end. Thanks!

**Comment by xczhanjun** [comment]
great
