### ISSUE TITLE
add different port option

### ISSUE THREAD

**Issue by badsmoke** [mjxu96/carlaviz#13]
Can you please add an option that the api can run on another port.

i would like to run carlaviz behind a reverse proxy and https without having to release port 8080.

**Comment by wx9698** [comment]
Sure, that should be simple.

By the way, this application also needs to export port 8081 to let the frontend communicate with backend as well. If you want to use the drawing functionality, it also needs 8089 port. I am thinking of adding a config file to change these settings.

**Comment by badsmoke** [comment]
thank you very much.

normal white you solve this by a subdir

e.g.

hostname/ = gui
hostname/api = communication to backend
hostname/draw_api = drawing communication

you only have to open one port, in my case port 443, so that I can run everything encrypted and without certificate errors via https

**Comment by mjxu96** [comment]
Although this is an old issue, I think we can resolve this by adding reverse proxy. Port customization is added in https://github.com/mjxu96/carlaviz/pull/62
