### ISSUE TITLE
broken when changing map

### ISSUE THREAD

**Issue by psarka** [mjxu96/carlaviz#19]
Running from official dockers

carla:0.9.10.1
carlaviz:latest

carla:0.9.10.1 has sumo 1.8 installed via

    RUN add-apt-repository ppa:sumo/stable
    RUN apt-get install -y sumo
    ENV SUMO_HOME=/usr/share/sumo

After carla and carlaviz have loaded, try to change the map (assuming Town01 is not loaded):

python config.py --map Town01 --host ...

Carlaviz stops working, and the log is continuosly spamming messages

    2021-03-05 14:35:28 [WARNING]  all traffic lights should be inserted first
    2021-03-05 14:35:28 [WARNING]  Stop sign 269 should be added first.

Is switching maps supposed to work?

**Comment by wx9698** [comment]
This is a known issue. CarlaViz will break when chaning maps. I am going to fix it in future releases.

**Comment by harishjartarghar** [comment]
when are you realeasing the new version of carlaviz,  having the change map feature

**Comment by mjxu96** [comment]
This is solved in https://github.com/mjxu96/carlaviz/pull/62
