### ISSUE TITLE
sending vehicle control input to server

### ISSUE THREAD

**Issue by Gr8ayu** [mjxu96/carlaviz#21]
Is carlaviz only for visualization ? Is there anyway to control the vehicles by sending control input to the server to steer/accelerate it? I couldn't find any related document to it. Please provide example or documentation if available.

**Comment by wx9698** [comment]
Yes, it is only for viz. I think Carla can be controlled remotely and it is already implemented by Carla team. There are remote ip and port settings in Carla python examples. https://github.com/carla-simulator/carla/blob/master/PythonAPI/examples/spawn_npc.py#L38
