### ISSUE TITLE
carlaviz stops/crashes when multiple frontend react server request for connection

### ISSUE THREAD

**Issue by harishjartarghar** [mjxu96/carlaviz#22]
we built our own docker image having only carlaviz in it and running the react client seperately and providing the serverURL accordingly. We found that this architecture works perfectly as well but the issue is when we have the carla and carlaviz running in remote server and provide the public serverURL to the two react server in the 2 different local system ,the carlaviz crashes i,e. there is no handshake taking place with the new request and old connection also breaks. does carlaviz is built to handle single connection or it can handle multiple request??. If it handles single connection how can we achieve to make it accept multiple connection.

**Comment by wx9698** [comment]
CarlaViz is built for multiple connections. Could you paste the error messages from the backend when it crashed?

**Comment by harishjartarghar** [comment]
hey, the multiple connection issue was not a problem. Everthing fine

**Comment by harishjartarghar** [comment]
is there a way to get server fps through carlaviz or some other way??

**Comment by mjxu96** [comment]
Yeah I think so but not yet implemented. Please re-open this issue if you still need this feature.
