### ISSUE TITLE
Changing port

### ISSUE THREAD

**Issue by Qtsho** [mjxu96/carlaviz#23]
Hi, wx9698,

thank you for your work with Carlaviz.

I noticed that the default port is 8080 as in:
"3. Open the localhost Open your web browser and go to http://127.0.0.1:8080/. carlaviz runs by default in port 8080. The output should be similar to the following."

Are there any ways to change this port to a different one directly from the Run command? (I wanted to change into 8003 as requested)

Thank you.

**Comment by wx9698** [comment]
If you are runing a containerized CarlaViz, you should be able to map the internal port to some other external port. https://docs.docker.com/config/containers/container-networking/#published-ports This might give you some hint.

**Comment by Qtsho** [comment]
Hello, 

thanks for the response. I am running containerized Carlaviz with this cmd:

docker run -p 8003:8080 -it -e CARLAVIZ_HOST_IP=localhost -e CARLA_SERVER_IP=localhost  -e CARLA_SERVER_PORT=2000 mjxu96/carlaviz:latest

but we cant see any thing displayed as shown:

![image](https://user-images.githubusercontent.com/37075262/115266928-ee1c3a80-a138-11eb-93d6-0134443c79ec.png)

**Comment by wx9698** [comment]
@Qtsho CarlaViz needs internal port 8081 to be mapped out to external port 8081 as well~

**Comment by jewes** [comment]
> @Qtsho CarlaViz needs internal port 8081 to be mapped out to external port 8081 as well~

and 8081 must be mapped to 8081 on the host. mapping it to a different port will not work. right?

**Comment by mjxu96** [comment]
This has been solved in https://github.com/mjxu96/carlaviz/pull/62
