### ISSUE TITLE
Draw polygons with carla painter

### ISSUE THREAD

**Issue by Gruensil** [mjxu96/carlaviz#26]
I haven't worked a lot with carlaviz and was wondering about the capabilities of adding my own graphic elements to the visualization. I found that the carla painter supports drawing polylines, points and text, but no polygons. The backend uses xviz for the drawing, which does support polygons, circles, images and whatnot. Is there a reason for this limitation that I should know of or could I simply extend the functionality? Or is this even already planned/implemented?

**Comment by mjxu96** [comment]
@Gruensil It is just because I did not implement it.... 

It should be easy to add more graphics. Related codes are in backend/src/backend/proxy/drawing_proxy.cpp. You are welcomed to add more functionalities.😄

**Comment by Gruensil** [comment]
Oh alright, I figured. Thanks for very quick response! 🙌
