### ISSUE TITLE
All traffic lights in carlaviz turn green

### ISSUE THREAD

**Issue by xrispa-m** [mjxu96/carlaviz#32]
I'm trying to run Carla with Sumo and Carlaviz. I've managed to synchronize Carla (client) and Sumo (server), so the vehicles move in Carla based on the routes from Sumo. However, all the traffic lights in Carlaviz are green instead of following the traffic light logic from Sumo. When I run the run_synchronization.py the traffic light manager is Sumo. Shouldn't those changes be depicted on Carlaviz too? I'm using Carla 0.9.11 and Sumo 1.7.0.

**Comment by mjxu96** [comment]
Please re-open this issue if you still have the same problem in the latest CarlaViz.
