### ISSUE TITLE
pure black image is shown regularly in the camera image stream

### ISSUE THREAD

**Issue by jewes** [mjxu96/carlaviz#35]
In some cases, pure black image is shown regularly in the camera image stream(like once a second, a pure black image is shown followed by correct camera image, and so on....)

**Comment by mjxu96** [comment]
This is a known issue when streaming images on Windows or streaming very quickly on Linux. I am working on a fix.

**Comment by mjxu96** [comment]
This should be fixed in https://github.com/mjxu96/carlaviz/pull/62
