### ISSUE TITLE
Launch backend and refresh

### ISSUE THREAD

**Issue by ddelvecchioara** [mjxu96/carlaviz#38]
Carla: 0.9.10-1
Carlaviz: 0.9.10

I am getting a Launch backend and refresh issue. I am attempting to run Carla and Carlaviz on an Azure Linux vm and use Carlaviz to stream the sessions to a website connected to the virtual machine. I have both Carla and Carlaviz running and can see Carlaviz in the browser at localhost:8080 working correctly.

When I connect to the website though and direct it to the Carlaviz portion all I can see is the Carlaviz message that says launch backend and refresh. Even though Carlaviz is running correctly when I view it directly on the vm.

Any help would be appreciated. Even if the response is that Carlaviz will not function correctly in the environment I am trying to use it in.
Thank you

**Comment by ddelvecchioara** [comment]
I could still use some help with this issue please.

**Comment by wuhanstudio** [comment]
Perhaps you can open the browser console (F12) to see if there's any error showing up there.

**Comment by mjxu96** [comment]
When you run CarlaViz in a remote server, please make sure that you have set the correct ip address of that server to environment variable `CARLAVIZ_BACKEND_HOST` when running the docker run command.

**Comment by mjxu96** [comment]
Please re-open this issue if you still have the problem in CarlaViz 0.9.14.
