### ISSUE TITLE
Connection to Carla Server is failed - Carla 0.9.12

### ISSUE THREAD

**Issue by newzoel** [mjxu96/carlaviz#39]
![carlaviz_issue](https://user-images.githubusercontent.com/29156573/134994818-958339ff-ceb0-45b0-b172-5d8ad3d1e99e.png)

Hello,

Anyone know what happened above? The status are below:
- Build & Run Carla from source (latest) on Windows
- Build & Run Carlaviz from docker as instructed on this page https://carla.readthedocs.io/en/latest/plugins_carlaviz/
- Carla Simulator is already running and tested with the scripts from PythonAPI/examples
- But there it is when start running carlaviz from docker with command as instructed on this page https://carla.readthedocs.io/en/latest/plugins_carlaviz/

Thank You

**Comment by mjxu96** [comment]
Hi we don't have CarlaViz for Carla 0.9.12.

**Comment by mjxu96** [comment]
Hi CarlaViz 0.9.12 has been released. Could you have a try and see if it works?

**Comment by newzoel** [comment]
Hi Thanks for notifying me.

I just tried it and it works!!!
Thanks for working on this version. If I may know, I would like to know how carlaviz works (backend).
Let me know if u have any references or documentation of carlaviz. I might want to contribute for carlaviz

Thanks again mjxu96 and team!

**Comment by mjxu96** [comment]
Not sure if you are still interested, but yeah I am looking for contributors to help maintain and develop CarlaViz. Please leave comments here or contact me via email if you are still interested in the project.

**Comment by RiaMatapurkar** [comment]
Hi, I have Carla 9.14 and get the following error when I run the command:
docker pull mjxu96/carlaviz:0.9.14.1 from https://github.com/mjxu96/carlaviz/tree/master

[2023-11-09 11:27:44.271] [info] CarlaViz will host websocket server on 0.0.0.0:8081
[2023-11-09 11:27:44.272] [info] CarlaViz websocket server starts.
[2023-11-09 11:27:44.272] [info] CarlaViz is trying to connect to Carla simulator on localhost:2000
[2023-11-09 11:27:44.273] [error] Connection to simulator failed for Connection refused
[2023-11-09 11:27:45.273] [info] CarlaViz is trying to connect to Carla simulator on localhost:2000
[2023-11-09 11:27:45.274] [error] Connection to simulator failed for Connection refused
[2023-11-09 11:27:46.274] [info] CarlaViz is trying to connect to Carla simulator on localhost:2000
[2023-11-09 11:27:46.275] [error] Connection to simulator failed for Connection refused
[2023-11-09 11:27:47.275] [info] CarlaViz is trying to connect to Carla simulator on localhost:2000
[2023-11-09 11:27:47.275] [error] Connection to simulator failed for Connection refused
[2023-11-09 11:27:48.276] [critical] Max retry times 3 passed when connecting to simulator, aborting...
terminate called after throwing an instance of 'std::runtime_error'
  what():  Max retry times 3 passed when connecting to simulator, aborting...
./docker/run.sh: line 5:    27 Aborted                 ./backend/bin/backend $@

Would appreciate any help!

**Comment by PierceG6** [comment]
same issue here, did you solve it?

**Comment by mjxu96** [comment]
hi @PierceG6 @RiaMatapurkar what is your docker run command and is your Carla simulator on the same host of CarlaViz container?

**Comment by PierceG6** [comment]
thanks for the reply, @mjxu96 
I tried to use >docker pull mjxu96/carlaviz:latest , it succeed. but when i tried >docker run -it -e CARLAVIZ_HOST_IP=59.10.147.138 -e CARLA_SERVER_IP=host.docker.internal -e CARLA_SERVER_PORT=2000 -p 8080-8081:8080-8081 -p 8089:8089 mjxu96/carlaviz:latest. this is what came out:
[2024-04-01 16:03:12.630] [info] CarlaViz is trying to connect to Carla simulator on localhost:2000
[2024-04-01 16:03:12.632] [error] Connection to simulator failed for Connection refused
[2024-04-01 16:03:13.632] [info] CarlaViz is trying to connect to Carla simulator on localhost:2000
[2024-04-01 16:03:13.633] [error] Connection to simulator failed for Connection refused
[2024-04-01 16:03:14.633] [info] CarlaViz is trying to connect to Carla simulator on localhost:2000
[2024-04-01 16:03:14.633] [error] Connection to simulator failed for Connection refused
[2024-04-01 16:03:15.633] [critical] Max retry times 3 passed when connecting to simulator, aborting...
terminate called after throwing an instance of 'std::runtime_error'
  what():  Max retry times 3 passed when connecting to simulator, aborting...
./docker/run.sh: line 5:    23 Aborted                 ./backend/bin/backend $@

THEN, i tried the 0.9.10 version. I succeed, but when I open http://127.0.0.1:8080/ , it shows launch the backend and refresh, but the commandline states this:
Launching backend.
2024-04-01 16:08:00 [INFO]     Connecting to Carla Server on host.docker.internal:2000...
2024-04-01 16:08:00 [INFO]     Connected to Carla Server, Server version is: 0.9.15
WARNING: Version mismatch detected: You are trying to connect to a simulator that might be incompatible with this API
WARNING: Client API version     = 0.9.10
WARNING: Simulator API version  = 0.9.15
./run.sh: line 16:     7 Segmentation fault      ./carlaviz/backend/bin/backend ${CARLA_SERVER_IP} ${CARLA_SERVER_PORT}
Backend launched.
I am so confused, i will be grateful for your help

**Comment by mjxu96** [comment]
hi the docker run command has been changed after CarlaViz 0.9.14. Could you check the latest document?

And please use the same version of CarlaViz as Carla, e.g. use CarlaViz 0.9.15 for Carla 0.9.15.

**Comment by mjxu96** [comment]
by the way, your IP in your reply looks like a public IP. You might want to hide it for safety.

**Comment by RiaMatapurkar** [comment]
@mjxu96 Yes both are on the same host

**Comment by RiaMatapurkar** [comment]
command-->docker pull mjxu96/carlaviz:0.9.14
error --> during connect: this error may indicate that the docker daemon is not running: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/images/create?fromImage=mjxu96%2Fcarlaviz&tag=0.9.14": open //./pipe/docker_engine: The system cannot find the file specified.

This is what I see now.

**Comment by mjxu96** [comment]
> during connect: this error may indicate that the docker daemon is not running: Post

Could you try 0.9.14.1 or 0.9.15? And could you check if you can pull other non-carlaviz images?

**Comment by PierceG6** [comment]
@mjxu96  Thanks for the reply. 
I tried the latest docker run command, the pulling was successful, but it shows error that not able to connect to the simulator. Could you please inform my next step, Thanks!

![893dd71a3c67ac96c5376748cafe6b5](https://github.com/mjxu96/carlaviz/assets/158272485/d7c99924-3ae4-4360-b4af-210918348fc0)

**Comment by mjxu96** [comment]
looks like it is almost there. Could you try to put the command into one line and discard the \ in the command?

**Comment by RiaMatapurkar** [comment]
@mjxu96 Thanks for all your suggestions I will try with 9.15 but my carla version is 9.14 source build, would that not be a problem?

**Comment by mjxu96** [comment]
Could you try CarlaViz 0.9.14.1? It can work with Carla 0.9.14

**Comment by PierceG6** [comment]
Thanks! @mjxu96 i tried this command ( docker run -it --network="host" mjxu96/carlaviz:0.9.15 --simulator_host localhost --simulator_port 2000). BUT it came out the same result (Connection to simulator failed for Connection refused).

**Comment by RiaMatapurkar** [comment]
@mjxu96 Unfortunatly I get the same error as before:

 error during connect: this error may indicate that the docker daemon is not running: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/images/create?fromImage=mjxu96%2Fcarlaviz&tag=0.9.14.1": open //./pipe/docker_engine: The system cannot find the file specified.

**Comment by mjxu96** [comment]
@RiaMatapurkar could you check if you can pull other images from dockerhub? This error seems like your local docker daemon problem.

FYI the carlaviz images are hosted at https://hub.docker.com/r/mjxu96/carlaviz/tags

**Comment by RiaMatapurkar** [comment]
@mjxu96 I was able to but I will just check again to see if there is a problem on my end! Thanks for all your help, I will write you an update on Monday

**Comment by PierceG6** [comment]
@mjxu96 Thank you for your help!! now I can run the carlaviz.
