### ISSUE TITLE
Websocket connection to 127.0.0.1:8081 failed

### ISSUE THREAD

**Issue by duongtran11** [mjxu96/carlaviz#40]
Hi, I'm using Carla Simulator built from source. 
When I run Carla Simulator (make launch then hit play), then I run docker image with `docker run -it --network="host" -e CARLAVIZ_HOST_IP=localhost -e CARLA_SERVER_IP=localhost -e CARLA_SERVER_PORT=2000 mjxu96/carlaviz:latest`
I got this error in the browser
![Screenshot from 2021-10-26 11-25-33](https://user-images.githubusercontent.com/67900559/138809246-ec84b45d-1b7c-4165-85a1-62257eeaf2a8.png)

This is output from `sudo netstat -nlp`
![Screenshot from 2021-10-26 11-29-32](https://user-images.githubusercontent.com/67900559/138809295-de70a727-1088-412a-9761-679c478841e7.png)

This is output from `netstat -int`
![Screenshot from 2021-10-26 11-29-44](https://user-images.githubusercontent.com/67900559/138809325-d3bd1e60-007f-479e-9f85-19c8adc5a0b4.png)

**Comment by mjxu96** [comment]
Hi CarlaViz 0.9.12 has been released. Could you have a try to see if it works?

**Comment by chenzhengxi** [comment]
use 8080

**Comment by mjxu96** [comment]
Please re-open this issue if you still have the problem in CarlaViz 0.9.14.
