### ISSUE TITLE
Will you release a new docker which fix for carla version 0.9.12?

### ISSUE THREAD

**Issue by aifei7320** [mjxu96/carlaviz#41]

**Comment by mjxu96** [comment]
I really hope I could have more time to maintain this project but I am quite busy this quarter. Maybe I can find some time to update this repo this month.

**Comment by aifei7320** [comment]
Make sure you have launched the Carla server.
Launching backend.
2021-11-05 07:45:44 [INFO]     Connecting to Carla Server on localhost:2000...
2021-11-05 07:45:44 [INFO]     Connected to Carla Server, Server version is: 0.9.12
WARNING: Version mismatch detected: You are trying to connect to a simulator that might be incompatible with this API
WARNING: Client API version     = 0.9.11
WARNING: Simulator API version  = 0.9.12
Backend launched.
Launching frontend
[....] Restarting nginx: nginx2021/11/05 07:45:45 [notice] 42#42: using the "epoll" event method
2021/11/05 07:45:45 [notice] 42#42: nginx/1.20.0
2021/11/05 07:45:45 [notice] 42#42: built by gcc 8.3.0 (Debian 8.3.0-6)
2021/11/05 07:45:45 [notice] 42#42: OS: Linux 5.4.0-89-generic
2021/11/05 07:45:45 [notice] 42#42: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2021/11/05 07:45:45 [notice] 43#43: start worker processes
2021/11/05 07:45:45 [notice] 43#43: start worker process 44
2021/11/05 07:45:45 [notice] 43#43: start worker process 45
2021/11/05 07:45:45 [notice] 43#43: start worker process 46
2021/11/05 07:45:45 [notice] 43#43: start worker process 47
2021/11/05 07:45:45 [notice] 43#43: start worker process 49
2021/11/05 07:45:45 [notice] 43#43: start worker process 50
2021/11/05 07:45:45 [notice] 43#43: start worker process 51
2021/11/05 07:45:45 [notice] 43#43: start worker process 52
2021/11/05 07:45:45 [notice] 43#43: start worker process 53
2021/11/05 07:45:45 [notice] 43#43: start worker process 54
2021/11/05 07:45:45 [notice] 43#43: start worker process 55
2021/11/05 07:45:45 [notice] 43#43: start worker process 56
2021/11/05 07:45:45 [notice] 43#43: start worker process 57
2021/11/05 07:45:45 [notice] 43#43: start worker process 58
2021/11/05 07:45:45 [notice] 43#43: start worker process 59
2021/11/05 07:45:45 [notice] 43#43: start worker process 60
. ok
Frontend launched. Please open your browser

When i open my browser, there is nothing but "launch backend and refresh" showed out. And in F12 window，i can see errors 
![image](https://user-images.githubusercontent.com/24615852/140476206-476f867f-f13b-452e-95d6-419acd960d3a.png)

**Comment by mjxu96** [comment]
Hi CarlaViz 0.9.12 is released. Please have a try.
