### ISSUE TITLE
does the "y" position misstakely flipped?

### ISSUE THREAD

**Issue by furyNerd** [mjxu96/carlaviz#52]
use the latest version (0.9.13), and the test code is as follow:

```
import time
import carla
from carla_painter import CarlaPainter


client = carla.Client('localhost', 2000)
client.set_timeout(2.0)
painter = CarlaPainter('localhost', 8089)


painter.draw_texts("hihi",[7.0, 8.0, 9.0])

time.sleep(200)

```

carla client and carla-viz were started as default, but the "hihi" is show as 

![图片](https://user-images.githubusercontent.com/42192954/178437842-9502b39e-1519-429f-a0e5-7a5d2e629bae.png)

is this right?

**Comment by mjxu96** [comment]
I remember the root cause is the y axis is flapped in the Carla coordinate... I think I forget to change the behavior in the Painter.
