### ISSUE TITLE
The WebSocket handshake Connection field is missing the upgrade token

### ISSUE THREAD

**Issue by excep** [mjxu96/carlaviz#55]
I did everything and everything went right just like the instructions and in the video on youtube, but when I open http://localhost:8089/ in the browser I get this error message both in the browser and in the terminal saying : The WebSocket handshake Connection field is missing the upgrade token. 
And I have no clue what's wrong !! 
Help por favor if you know what may be wrong !!

**Comment by TobiMiller** [comment]
The Port is 8080.

**Comment by mjxu96** [comment]
Please use 8080.
