### ISSUE TITLE
support for Carla version 0.9.14

### ISSUE THREAD

**Issue by doddsy2018** [mjxu96/carlaviz#56]
will you release carlaviz for Carla version 0.9.14?

**Comment by mjxu96** [comment]
Yeah I will take a look when I have some time.

**Comment by ksuszka** [comment]
I was able to run CarlaViz with Carla 0.9.14 after:
- replacing backend/third_party/LibCarla folder content with https://github.com/carla-simulator/carla/tree/0.9.14/LibCarla
- Updating boost version from 1.72.0 to 1.80.0 in build scripts (version used in Carla 0.9.14)
- Updated build scripts to download Carla 0.9.14 release version (https://carla-releases.s3.eu-west-3.amazonaws.com/Linux/CARLA_0.9.14.tar.gz)

Unfotunately, this version can no longer connect to Carla 0.9.13.

**Comment by mjxu96** [comment]
I've been working on this recently. Let me know if you want any more features or bug fixes with the new version as well in this [discussion](https://github.com/mjxu96/carlaviz/discussions/60).

**Comment by mjxu96** [comment]
This has been resolved in https://github.com/mjxu96/carlaviz/pull/62
