### ISSUE TITLE
New Vehicle

### ISSUE THREAD

**Issue by EHxxx** [mjxu96/carlaviz#57]
Can I change the vehicle model in Carlaviz?? 

I executed the manual_control.py and Carlaviz, then I changed my vehicle model pushing the backspace button.
However, the vehicle model didn't change in the carlaviz.(localhost:8080)

I need this information because I want to add a new vehicle and run it.
Please help me

**Comment by mjxu96** [comment]
Hi this should be a visualization issue in the frontend. Unfortunately, I am not an expert on it. You may check the frontend library repo for more information. As long as there are options to change model in the frontend, it should be easy to add an option in the backend as well.
