### ISSUE TITLE
Carla 0.9.13 in remote Docker: "Launch the backend and refresh"

### ISSUE THREAD

**Issue by defrag-bambino** [mjxu96/carlaviz#58]
Hi,
just like #6, I have the issue of my browser window staying empty exept for the message "CarlaViz   Launch the backend and refresh". I have tried the fixes proposed in the two other issues, but they do not seem to work for me.
I am running both Carla and CarlaViz in a remote docker container and accessing the browser page through a VPN into their network.
My terminal output is:

> Make sure you have launched the Carla server.
Launching backend.
cat: output.txt: No such file or directory
2023-02-14 16:28:24 [INFO]     Connecting to Carla Server on 172.17.0.16:2000...
2023-02-14 16:28:24 [INFO]     Connected to Carla Server, Server version is: 0.9.13
2023-02-14 16:28:24 [INFO]     Waiting for a drawing client to connect. Listening to port 8089....
2023-02-14 16:28:24 [INFO]     Waiting for a frontend to connect. Listening to port 8081....
Backend launched.
Launching frontend
Restarting nginx: nginx2023/02/14 16:28:25 [notice] 282#282: using the "epoll" event method
2023/02/14 16:28:25 [notice] 282#282: nginx/1.20.2
2023/02/14 16:28:25 [notice] 282#282: built by gcc 10.2.1 20210110 (Debian 10.2.1-6) 
2023/02/14 16:28:25 [notice] 282#282: OS: Linux 5.4.0-91-generic
2023/02/14 16:28:25 [notice] 282#282: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2023/02/14 16:28:25 [notice] 283#283: start worker processes
2023/02/14 16:28:25 [notice] 283#283: start worker process 285
2023/02/14 16:28:25 [notice] 283#283: start worker process 286
2023/02/14 16:28:25 [notice] 283#283: start worker process 287
2023/02/14 16:28:25 [notice] 283#283: start worker process 288
2023/02/14 16:28:25 [notice] 283#283: start worker process 290
2023/02/14 16:28:25 [notice] 283#283: start worker process 291
2023/02/14 16:28:25 [notice] 283#283: start worker process 292
2023/02/14 16:28:25 [notice] 283#283: start worker process 293
2023/02/14 16:28:25 [notice] 283#283: start worker process 294
2023/02/14 16:28:25 [notice] 283#283: start worker process 296
2023/02/14 16:28:25 [notice] 283#283: start worker process 297
2023/02/14 16:28:25 [notice] 283#283: start worker process 298
2023/02/14 16:28:25 [notice] 283#283: start worker process 299
2023/02/14 16:28:25 [notice] 283#283: start worker process 301
2023/02/14 16:28:25 [notice] 283#283: start worker process 302
2023/02/14 16:28:25 [notice] 283#283: start worker process 303
2023/02/14 16:28:25 [notice] 283#283: start worker process 304
2023/02/14 16:28:25 [notice] 283#283: start worker process 305
2023/02/14 16:28:25 [notice] 283#283: start worker process 307
2023/02/14 16:28:25 [notice] 283#283: start worker process 308
2023/02/14 16:28:25 [notice] 283#283: start worker process 309
.
2023/02/14 16:28:25 [notice] 283#283: start worker process 310
Frontend launched. Please open your browser
2023/02/14 16:28:25 [notice] 283#283: start worker process 312
2023/02/14 16:28:25 [notice] 283#283: start worker process 313
2023/02/14 16:28:25 [notice] 283#283: start worker process 314
2023/02/14 16:28:25 [notice] 283#283: start worker process 315
...............bunch more of these..............
2023/02/14 16:28:25 [notice] 283#283: start worker process 545
141.83.86.40 - - [14/Feb/2023:16:29:20 +0000] "GET / HTTP/1.1" 200 266 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "-"
141.83.86.40 - - [14/Feb/2023:16:29:21 +0000] "GET /bundle.js HTTP/1.1" 200 3222259 "http://141.83.108.201:49316/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "-"
141.83.86.40 - - [14/Feb/2023:16:29:21 +0000] "GET /573fe91c6c748074195655e1f0159864.png HTTP/1.1" 200 7788 "http://141.83.108.201:49316/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "-"
141.83.86.40 - - [14/Feb/2023:16:29:21 +0000] "GET /favicon.ico HTTP/1.1" 404 555 "http://141.83.108.201:49316/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "-"
141.83.86.40 - - [14/Feb/2023:16:29:23 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "-"
141.83.86.40 - - [14/Feb/2023:16:38:18 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "-"
2023-02-14 16:42:44 [INFO]     Drawing client 0 connected

I am especially curious about the line `cat: output.txt: No such file or directory` right after the Backend tries to start. After this nginx seems to restart - I am not sure if this is the desired chain of events. Is the backend maybe crashing while it starts?

Thanks

**Comment by mjxu96** [comment]
Please re-open this issue if still have the same problem in latest CarlaViz.
