### ISSUE TITLE
carlaViz with carla 0.9.14

### ISSUE THREAD

**Issue by sommsmartin** [mjxu96/carlaviz#59]
I am trying to use CarlaViz with Carla 0.9.14. 
![image](https://user-images.githubusercontent.com/127199235/225372199-d18f226a-d3b4-4fd8-83fe-50ab62dc3b97.png)
Nothing gets displayed in the browser.
When i try to run the example.py of the latest carlaviz release, I get the following error and cant figure out what the issue might be. 
![image](https://user-images.githubusercontent.com/127199235/225368058-34afc5f0-e571-4b91-807d-94d1616084e9.png)

Do you have any idea? Does it have to do with the newer Carla version?

Best regards,
Martin

**Comment by mjxu96** [comment]
I've been working on this recently. Let me know if you want any more features or bug fixes with the new version as well in this [discussion](https://github.com/mjxu96/carlaviz/discussions/60).

**Comment by mjxu96** [comment]
Done in https://github.com/mjxu96/carlaviz/pull/62
