### ISSUE TITLE
How to remove the graphics of these buildings

### ISSUE THREAD

**Issue by ZScai** [mjxu96/carlaviz#63]
![image](https://github.com/mjxu96/carlaviz/assets/86775125/6d942e62-f7f2-451f-9a68-41e1780a8099)
carla: 0.9.14
carlaviz: 0.9.14
These buildings block the perspective of the car, how should we remove them？
I am a beginner who has just used Carlar. If you can answer, thank you very much。

**Comment by mjxu96** [comment]
Append this option to the end of `docker run` and set it to `false`
```bash
    -translation_allow_static_objects (Whether to show static objects)
      type: bool default: true
```

**Comment by ZScai** [comment]
> Append this option to the end of and set it to `docker run``false`
> 
> ```shell
>     -translation_allow_static_objects (Whether to show static objects)
>       type: bool default: true
> ```

![image](https://github.com/mjxu96/carlaviz/assets/86775125/7297997a-2393-40d4-9b3c-7ddae415f93b)
I executed this command in Docker, but it doesn't seem to have taken effect

**Comment by ZScai** [comment]
> I think should be
> 
> ```shell
> --translation_allow_static_objects=false
> ```

Thank you very much for it being effective
