### ISSUE TITLE
How to get trafficlights and buildings shown?

### ISSUE THREAD

**Issue by lygbuaa** [mjxu96/carlaviz#68]
Hi, very great work!
When I am running the example (with carla 0.9.13), I can get the map and ego vehicle shown, but without any trafficlights and buildings. Like this:
![image](https://github.com/mjxu96/carlaviz/assets/30497805/1317a9a6-4a71-4fb7-945e-7b4cf0be6602)

So, how do you get  trafficlights and buildings shown on your demo2.jpg ?

**Comment by mjxu96** [comment]
Hi Carlaviz:0.9.13 does not support building display. You may want to upgrade to the latest version with latest Carla simulator.
